# config/config.yaml
app:
  name: "user-crud-system"
  version: "1.0.0"
  env: "development"  # development, staging, production

server:
  port: 8080
  timeout: 30s
  read_timeout: 15s
  write_timeout: 15s
  debug: true
  cors_allowed_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"

database:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "admin"
  dbname: "user_management_db"
  sslmode: "disable"
  timezone: "Asia/Tehran"
  max_open_conns: 25
  max_idle_conns: 5
  max_lifetime: 30  # minutes

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 2
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s

jwt:
  secret: "your-super-secure-jwt-secret-key-min-32-chars"
  refresh_secret: "your-super-secure-refresh-secret-key-min-32-chars"
  access_token_expire: 15m    # 15 minutes
  refresh_token_expire: 168h  # 7 days
  issuer: "user-crud-app"

password:
  min_length: 8
  require_uppercase: true
  require_lowercase: true
  require_digits: true
  require_special_chars: false
  max_attempts: 5
  lockout_time: 30  # minutes

otp:
  digits: 6
  expire_time: 120    # seconds
  max_attempts: 3
  resend_delay: 60    # seconds
  block_duration: 300 # seconds after max attempts
  allowed_chars: "0123456789"

logging:
  level: "debug"  # debug, info, warn, error
  format: "json"  # json, text
  output: "stdout" # stdout, file
  file_path: "./logs/app.log"
  max_size: 100   # MB
  max_backups: 10
  max_age: 30     # days

smtp:
  host: "smtp.gmail.com"
  port: 587
  username: "your-email@gmail.com"
  password: "your-app-password"
  from: "noreply@yourdomain.com"
  ssl: false

sms:
  provider: "kavenegar"  # kavenegar, melipayamak, etc.
  api_key: "your-api-key"
  sender: "3000xxx"
  template: "verify"